import { db } from "./db";
import { ingredients } from "@shared/schema";
import { type InsertIngredient } from "@shared/schema";

// 薬膳食典 バッチ2: や〜わ行 + 追加食材（80種類）
const batch2Ingredients: InsertIngredient[] = [
  // や行
  { name: "やまいも", nameEn: "Japanese Yam", nameAlt: ["山芋", "ヤマイモ"], scientificName: "Dioscorea japonica", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "lung", "kidney"], effects: ["益気養陰", "補脾肺腎", "固精止帯"], contraindications: ["実邪者忌用"], nutrition: { calories: 65, mucin: "高含有", diosgenin: "含有" }, commonUses: ["とろろ", "煮物", "お好み焼き"], preparationMethods: ["すりおろす", "煮る", "焼く"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  { name: "ゆず", nameEn: "Yuzu", nameAlt: ["柚子", "ユズ"], scientificName: "Citrus junos", category: "fruit", nature: "warm", flavor: ["sour", "bitter"], element: "wood", meridians: ["liver", "stomach"], effects: ["理気和中", "化痰止咳"], contraindications: ["陰虚者慎用"], nutrition: { vitaminC: 150, limonene: "高含有", yuzu_oil: "含有" }, commonUses: ["調味料", "香り付け", "柚子湯"], preparationMethods: ["絞る", "すりおろす"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  
  { name: "よもぎ", nameEn: "Mugwort", nameAlt: ["蓬", "ヨモギ"], scientificName: "Artemisia princeps", category: "herb", nature: "warm", flavor: ["bitter", "spicy"], element: "wood", meridians: ["liver", "spleen", "kidney"], effects: ["温経止血", "散寒止痛", "祛湿止痒"], contraindications: ["陰虚血熱者忌用"], nutrition: { chlorophyll: "高含有", flavonoids: "含有" }, commonUses: ["草餅", "お茶", "入浴剤"], preparationMethods: ["茹でる", "乾燥", "煎じる"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  
  // ら行
  { name: "らっきょう", nameEn: "Rakkyo", nameAlt: ["辣韮", "ラッキョウ"], scientificName: "Allium chinense", category: "vegetable", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "stomach"], effects: ["通陽散結", "行気導滞"], contraindications: ["陰虚火旺者慎用"], nutrition: { fructans: "高含有", allicin: "含有" }, commonUses: ["甘酢漬け", "カレーの付け合わせ"], preparationMethods: ["漬ける"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "りんご", nameEn: "Apple", nameAlt: ["林檎", "リンゴ"], scientificName: "Malus domestica", category: "fruit", nature: "cool", flavor: ["sweet", "sour"], element: "wood", meridians: ["spleen", "lung"], effects: ["生津止渇", "潤肺除煩", "健脾益胃"], contraindications: [], nutrition: { calories: 57, fiber: 1.5, pectin: "高含有", polyphenols: "含有" }, commonUses: ["生食", "ジュース", "アップルパイ"], preparationMethods: ["生食", "煮る", "焼く"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  
  { name: "レタス", nameEn: "Lettuce", nameAlt: ["lettuce"], scientificName: "Lactuca sativa", category: "vegetable", nature: "cool", flavor: ["sweet", "bitter"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["清熱安神", "利尿通乳"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 12, folate: 73, lactucarium: "含有" }, commonUses: ["サラダ", "サンドイッチ", "炒め物"], preparationMethods: ["生食", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "れんこん", nameEn: "Lotus Root", nameAlt: ["蓮根", "レンコン"], scientificName: "Nelumbo nucifera", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["heart", "spleen", "stomach"], effects: ["清熱涼血", "散瘀止血", "健脾開胃"], contraindications: [], nutrition: { calories: 66, vitaminC: 48, tannins: "含有", mucilage: "含有" }, commonUses: ["煮物", "きんぴら", "天ぷら"], preparationMethods: ["煮る", "炒める", "揚げる"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  
  // わ行
  { name: "わかめ", nameEn: "Wakame Seaweed", nameAlt: ["若布", "ワカメ"], scientificName: "Undaria pinnatifida", category: "seaweed", nature: "cold", flavor: ["salty"], element: "water", meridians: ["kidney", "liver", "stomach"], effects: ["清熱利水", "軟堅散結", "消痰"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 16, calcium: 100, iodine: "高含有", fucoidan: "高含有" }, commonUses: ["味噌汁", "酢の物", "サラダ"], preparationMethods: ["水で戻す", "茹でる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "わさび", nameEn: "Wasabi", nameAlt: ["山葵", "ワサビ"], scientificName: "Eutrema japonicum", category: "spice", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "stomach"], effects: ["開胃消食", "解毒殺菌", "活血散結"], contraindications: ["胃潰瘍者慎用"], nutrition: { isothiocyanates: "高含有", sinigrin: "含有" }, commonUses: ["薬味", "調味料"], preparationMethods: ["すりおろす"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  // 追加の主要食材
  { name: "あまえび", nameEn: "Sweet Shrimp", nameAlt: ["甘海老", "アマエビ"], scientificName: "Pandalus borealis", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["kidney", "stomach"], effects: ["補腎壮陽", "通乳"], contraindications: [], nutrition: { calories: 87, protein: 19.8, astaxanthin: "高含有" }, commonUses: ["刺身", "寿司"], preparationMethods: ["生食"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "あわび", nameEn: "Abalone", nameAlt: ["鮑", "アワビ"], scientificName: "Haliotis discus hannai", category: "protein", nature: "neutral", flavor: ["sweet", "salty"], element: "water", meridians: ["liver", "kidney"], effects: ["滋陰清熱", "平肝潜陽", "明目"], contraindications: [], nutrition: { calories: 73, protein: 12.7, taurine: "高含有", collagen: "含有" }, commonUses: ["刺身", "ステーキ", "煮物"], preparationMethods: ["生食", "焼く", "煮る"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "いくら", nameEn: "Salmon Roe", nameAlt: ["イクラ"], scientificName: "Oncorhynchus keta", category: "protein", nature: "warm", flavor: ["sweet", "salty"], element: "fire", meridians: ["liver", "kidney"], effects: ["補肝腎", "益精血", "健脾開胃"], contraindications: ["高脂血症者少量"], nutrition: { calories: 272, protein: 32.6, EPA_DHA: "極高含有", astaxanthin: "高含有" }, commonUses: ["寿司", "丼物", "おにぎり"], preparationMethods: ["漬ける", "そのまま"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "うに", nameEn: "Sea Urchin", nameAlt: ["海胆", "ウニ"], scientificName: "Hemicentrotus pulcherrimus", category: "protein", nature: "warm", flavor: ["sweet", "salty"], element: "water", meridians: ["liver", "kidney"], effects: ["補腎壮陽", "強精", "調経"], contraindications: ["アレルギー者注意"], nutrition: { calories: 120, protein: 16.0, EPA_DHA: "高含有" }, commonUses: ["刺身", "寿司", "パスタ"], preparationMethods: ["生食", "蒸す"], bestSeasons: ["spring", "summer"], synergisticWith: [], conflictsWith: [] },
  { name: "かつおぶし", nameEn: "Bonito Flakes", nameAlt: ["鰹節", "カツオブシ"], scientificName: "Katsuwonus pelamis", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾開胃"], contraindications: [], nutrition: { calories: 356, protein: 77.1, inosinic_acid: "極高含有" }, commonUses: ["だし", "ふりかけ", "お好み焼き"], preparationMethods: ["削る", "煎じる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "かんぴょう", nameEn: "Dried Gourd Strips", nameAlt: ["干瓢", "カンピョウ"], scientificName: "Lagenaria siceraria", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["清熱利水", "通便"], contraindications: [], nutrition: { calories: 258, fiber: 30.1, calcium: 250 }, commonUses: ["巻き寿司", "煮物"], preparationMethods: ["水で戻す", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "ぎんだら", nameEn: "Sablefish", nameAlt: ["銀鱈", "ギンダラ"], scientificName: "Anoplopoma fimbria", category: "protein", nature: "warm", flavor: ["sweet"], element: "water", meridians: ["spleen", "stomach"], effects: ["補虚労", "益気血"], contraindications: [], nutrition: { calories: 220, protein: 13.0, EPA_DHA: "極高含有" }, commonUses: ["西京焼き", "煮付け"], preparationMethods: ["焼く", "煮る"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "くらげ", nameEn: "Jellyfish", nameAlt: ["海月", "クラゲ"], scientificName: "Rhopilema esculentum", category: "protein", nature: "neutral", flavor: ["salty"], element: "water", meridians: ["liver", "kidney"], effects: ["清熱化痰", "消積潤腸"], contraindications: [], nutrition: { calories: 22, protein: 3.8, collagen: "高含有" }, commonUses: ["酢の物", "中華料理"], preparationMethods: ["塩抜き", "茹でる"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "グリーンピース", nameEn: "Green Peas", nameAlt: ["green peas"], scientificName: "Pisum sativum", category: "legume", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["健脾和中", "利水消腫"], contraindications: [], nutrition: { calories: 93, protein: 6.9, fiber: 7.7 }, commonUses: ["炒め物", "スープ", "サラダ"], preparationMethods: ["茹でる", "炒める"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "くるまえび", nameEn: "Kuruma Prawn", nameAlt: ["車海老", "クルマエビ"], scientificName: "Penaeus japonicus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["kidney", "stomach"], effects: ["補腎壮陽", "通乳", "托毒"], contraindications: ["皮膚病患者慎用"], nutrition: { calories: 97, protein: 21.6, taurine: "高含有" }, commonUses: ["天ぷら", "刺身", "塩焼き"], preparationMethods: ["揚げる", "生食", "焼く"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  
  { name: "こい", nameEn: "Carp", nameAlt: ["鯉", "コイ"], scientificName: "Cyprinus carpio", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["spleen", "kidney"], effects: ["健脾開胃", "利水消腫", "通乳"], contraindications: [], nutrition: { calories: 171, protein: 17.7, EPA_DHA: "含有" }, commonUses: ["洗い", "煮物", "鯉こく"], preparationMethods: ["生食", "煮る"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "こおりどうふ", nameEn: "Freeze-dried Tofu", nameAlt: ["凍り豆腐", "コオリドウフ", "高野豆腐"], scientificName: "Glycine max", category: "protein", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["健脾益気", "清熱潤燥"], contraindications: [], nutrition: { calories: 529, protein: 50.5, calcium: 630, iron: 7.5 }, commonUses: ["煮物", "炊き合わせ"], preparationMethods: ["水で戻す", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "ごぼうの種", nameEn: "Burdock Seed", nameAlt: ["牛蒡子", "ゴボウノタネ"], scientificName: "Arctium lappa", category: "herb", nature: "cold", flavor: ["spicy", "bitter"], element: "metal", meridians: ["lung", "stomach"], effects: ["疏散風熱", "宣肺透疹", "解毒利咽"], contraindications: ["気虚便溏者慎用"], nutrition: { arctiin: "含有", essential_oils: "含有" }, commonUses: ["薬用茶", "漢方薬"], preparationMethods: ["煎じる", "粉末化"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "こんぶ茶", nameEn: "Kelp Tea", nameAlt: ["昆布茶", "コンブチャ"], scientificName: "Laminaria japonica", category: "beverage", nature: "cold", flavor: ["salty"], element: "water", meridians: ["liver", "stomach", "kidney"], effects: ["軟堅散結", "消痰利水"], contraindications: ["脾胃虚寒者慎用"], nutrition: { iodine: "高含有", glutamic_acid: "高含有" }, commonUses: ["飲料", "調味料"], preparationMethods: ["溶かす"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "さくらんぼ", nameEn: "Cherry", nameAlt: ["桜桃", "サクランボ"], scientificName: "Prunus avium", category: "fruit", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾和胃"], contraindications: ["熱性病患者慎用"], nutrition: { calories: 60, anthocyanins: "含有", melatonin: "含有" }, commonUses: ["生食", "ジャム", "お菓子"], preparationMethods: ["生食", "煮る"], bestSeasons: ["spring", "summer"], synergisticWith: [], conflictsWith: [] },
  { name: "ささげ", nameEn: "Cowpea", nameAlt: ["大角豆", "ササゲ"], scientificName: "Vigna unguiculata", category: "legume", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "kidney"], effects: ["健脾補腎", "利水消腫"], contraindications: [], nutrition: { calories: 336, protein: 23.9, fiber: 18.6 }, commonUses: ["赤飯", "煮豆"], preparationMethods: ["煮る", "茹でる"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "さつまあげ", nameEn: "Fried Fish Cake", nameAlt: ["薩摩揚げ", "サツマアゲ"], scientificName: "Mixed fish", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾和胃"], contraindications: [], nutrition: { calories: 139, protein: 12.5, calcium: 80 }, commonUses: ["おでん", "煮物", "炒め物"], preparationMethods: ["煮る", "炒める", "焼く"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "さとうきび", nameEn: "Sugar Cane", nameAlt: ["甘蔗", "サトウキビ"], scientificName: "Saccharum officinarum", category: "sweetener", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["清熱生津", "和中止嘔"], contraindications: ["湿熱内盛者慎用"], nutrition: { sucrose: "極高含有", polyphenols: "含有" }, commonUses: ["砂糖", "飲料"], preparationMethods: ["搾る", "精製"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "さといもの茎", nameEn: "Taro Stem", nameAlt: ["芋茎", "サトイモノクキ", "ずいき"], scientificName: "Colocasia esculenta", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["stomach", "large_intestine"], effects: ["清熱化痰", "利水消腫"], contraindications: [], nutrition: { calories: 17, fiber: 2.3, calcium: 71 }, commonUses: ["酢の物", "煮物"], preparationMethods: ["茹でる", "漬ける"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  
  { name: "さんま", nameEn: "Pacific Saury", nameAlt: ["秋刀魚", "サンマ"], scientificName: "Cololabis saira", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補虚労", "強筋骨", "暖中"], contraindications: [], nutrition: { calories: 310, protein: 18.5, EPA: 1500, DHA: 2800 }, commonUses: ["塩焼き", "刺身", "蒲焼き"], preparationMethods: ["焼く", "生食", "煮る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "シークヮーサー", nameEn: "Shikuwasa", nameAlt: ["シークワーサー", "ヒラミレモン"], scientificName: "Citrus depressa", category: "fruit", nature: "cool", flavor: ["sour"], element: "wood", meridians: ["liver", "stomach"], effects: ["疏肝理気", "生津止渴"], contraindications: ["胃酸過多者慎用"], nutrition: { vitaminC: 30, nobiletin: "極高含有" }, commonUses: ["調味料", "ジュース"], preparationMethods: ["絞る"], bestSeasons: ["summer", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "しそ油", nameEn: "Perilla Oil", nameAlt: ["紫蘇油", "シソユ", "えごま油"], scientificName: "Perilla frutescens", category: "oil", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "spleen"], effects: ["潤肺止咳", "潤腸通便"], contraindications: ["痰湿内盛者慎用"], nutrition: { omega3: "極高含有", alpha_linolenic_acid: "極高含有" }, commonUses: ["調味料", "ドレッシング"], preparationMethods: ["かける"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "じゃがいも", nameEn: "Potato", nameAlt: ["馬鈴薯", "ジャガイモ"], scientificName: "Solanum tuberosum", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["和中養胃", "健脾利湿", "解毒消炎"], contraindications: ["発芽部分は有毒"], nutrition: { calories: 76, vitaminC: 35, potassium: 410 }, commonUses: ["煮物", "炒め物", "サラダ"], preparationMethods: ["煮る", "炒める", "揚げる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "しゅんぎく", nameEn: "Garland Chrysanthemum", nameAlt: ["春菊", "シュンギク"], scientificName: "Glebionis coronaria", category: "vegetable", nature: "cool", flavor: ["spicy", "sweet"], element: "wood", meridians: ["liver", "spleen"], effects: ["疏肝理気", "和胃消食", "清肺化痰"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 22, betaCarotene: 4500, calcium: 120 }, commonUses: ["鍋物", "おひたし", "天ぷら"], preparationMethods: ["茹でる", "炒める", "揚げる"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  
  { name: "しらたき", nameEn: "Shirataki Noodles", nameAlt: ["白滝", "シラタキ"], scientificName: "Amorphophallus konjac", category: "vegetable", nature: "cold", flavor: ["spicy"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["化痰消積", "解毒消腫", "通便"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 6, fiber: 2.9, glucomannan: "高含有" }, commonUses: ["すき焼き", "煮物", "鍋物"], preparationMethods: ["茹でる", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "すだち", nameEn: "Sudachi", nameAlt: ["酢橘", "スダチ"], scientificName: "Citrus sudachi", category: "fruit", nature: "cool", flavor: ["sour"], element: "wood", meridians: ["liver", "stomach"], effects: ["疏肝理気", "生津止渴", "消食化痰"], contraindications: ["胃酸過多者慎用"], nutrition: { vitaminC: 110, flavonoids: "高含有" }, commonUses: ["調味料", "薬味"], preparationMethods: ["絞る", "切る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "すっぽん", nameEn: "Soft-shelled Turtle", nameAlt: ["鼈", "スッポン"], scientificName: "Pelodiscus sinensis", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["liver", "kidney"], effects: ["滋陰補腎", "養血柔肝", "軟堅散結"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 197, protein: 16.4, collagen: "極高含有" }, commonUses: ["鍋物", "スープ"], preparationMethods: ["煮る", "蒸す"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "すもも", nameEn: "Plum", nameAlt: ["李", "スモモ", "プラム"], scientificName: "Prunus salicina", category: "fruit", nature: "neutral", flavor: ["sweet", "sour"], element: "wood", meridians: ["liver", "kidney"], effects: ["清肝除熱", "生津利水"], contraindications: ["多食傷脾胃"], nutrition: { calories: 44, anthocyanins: "含有", sorbitol: "含有" }, commonUses: ["生食", "ジャム", "果実酒"], preparationMethods: ["生食", "煮る", "漬ける"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  
  { name: "セリ", nameEn: "Japanese Parsley", nameAlt: ["芹", "セリ"], scientificName: "Oenanthe javanica", category: "vegetable", nature: "cool", flavor: ["sweet", "bitter"], element: "wood", meridians: ["liver", "lung"], effects: ["清熱利水", "止血調経"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 17, betaCarotene: 1900, folate: 110 }, commonUses: ["鍋物", "おひたし", "七草粥"], preparationMethods: ["茹でる", "生食"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "そば粉", nameEn: "Buckwheat Flour", nameAlt: ["蕎麦粉", "ソバコ"], scientificName: "Fagopyrum esculentum", category: "grain", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "large_intestine"], effects: ["健脾消積", "下気寬腸"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 361, protein: 12.0, rutin: "極高含有" }, commonUses: ["蕎麦", "クレープ", "お菓子"], preparationMethods: ["練る", "茹でる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "たけ", nameEn: "Bamboo", nameAlt: ["竹", "タケ"], scientificName: "Bambusa vulgaris", category: "herb", nature: "cold", flavor: ["sweet"], element: "wood", meridians: ["heart", "lung", "stomach"], effects: ["清熱化痰", "除煩止嘔"], contraindications: ["脾胃虚寒者慎用"], nutrition: { silica: "含有", fiber: "高含有" }, commonUses: ["薬用", "竹炭"], preparationMethods: ["煎じる", "炭化"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "たくあん", nameEn: "Pickled Daikon", nameAlt: ["沢庵", "タクアン"], scientificName: "Raphanus sativus", category: "fermented", nature: "cool", flavor: ["sweet", "salty"], element: "metal", meridians: ["lung", "stomach"], effects: ["消食下気", "開胃"], contraindications: [], nutrition: { calories: 27, fiber: 2.9, lactic_acid_bacteria: "含有" }, commonUses: ["漬物", "お茶漬け"], preparationMethods: ["漬ける", "発酵"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "たちうお", nameEn: "Largehead Hairtail", nameAlt: ["太刀魚", "タチウオ"], scientificName: "Trichiurus japonicus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補虚労", "益気血"], contraindications: [], nutrition: { calories: 266, protein: 16.5, EPA_DHA: "高含有" }, commonUses: ["塩焼き", "フライ", "煮付け"], preparationMethods: ["焼く", "揚げる", "煮る"], bestSeasons: ["summer", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "たにし", nameEn: "River Snail", nameAlt: ["田螺", "タニシ"], scientificName: "Cipangopaludina chinensis", category: "protein", nature: "cold", flavor: ["sweet"], element: "water", meridians: ["liver", "kidney", "bladder"], effects: ["清熱利水", "明目"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 34, protein: 7.5, calcium: 240 }, commonUses: ["煮物", "炒め物"], preparationMethods: ["茹でる", "炒める"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "たまご", nameEn: "Chicken Egg", nameAlt: ["卵", "タマゴ"], scientificName: "Gallus gallus", category: "protein", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "lung"], effects: ["滋陰潤燥", "養血安胎"], contraindications: [], nutrition: { calories: 151, protein: 12.3, lecithin: "高含有", vitamins: "全含有" }, commonUses: ["卵焼き", "ゆで卵", "お菓子"], preparationMethods: ["茹でる", "焼く", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "たらこ", nameEn: "Cod Roe", nameAlt: ["鱈子", "タラコ"], scientificName: "Gadus macrocephalus", category: "protein", nature: "warm", flavor: ["salty"], element: "water", meridians: ["kidney", "liver"], effects: ["補腎益精", "養血"], contraindications: ["高血圧者少量"], nutrition: { calories: 140, protein: 28.3, vitaminE: 6.6 }, commonUses: ["おにぎり", "パスタ", "焼き物"], preparationMethods: ["焼く", "漬ける"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "たら", nameEn: "Cod", nameAlt: ["鱈", "タラ"], scientificName: "Gadus macrocephalus", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["spleen", "stomach"], effects: ["健脾益気", "補虚労"], contraindications: [], nutrition: { calories: 77, protein: 17.6, taurine: "含有" }, commonUses: ["鍋物", "フライ", "煮付け"], preparationMethods: ["煮る", "焼く", "揚げる"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "たんぽぽ", nameEn: "Dandelion", nameAlt: ["蒲公英", "タンポポ"], scientificName: "Taraxacum officinale", category: "herb", nature: "cold", flavor: ["bitter", "sweet"], element: "fire", meridians: ["liver", "stomach"], effects: ["清熱解毒", "消腫散結", "利尿通淋"], contraindications: ["陽虚外寒者慎用"], nutrition: { inulin: "含有", vitamins: "豊富" }, commonUses: ["薬用茶", "サラダ"], preparationMethods: ["煎じる", "生食"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ちくわ", nameEn: "Fish Cake Tube", nameAlt: ["竹輪", "チクワ"], scientificName: "Mixed fish", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾開胃"], contraindications: [], nutrition: { calories: 121, protein: 12.2, calcium: 45 }, commonUses: ["おでん", "炒め物", "お弁当"], preparationMethods: ["焼く", "煮る", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "つくし", nameEn: "Horsetail", nameAlt: ["土筆", "ツクシ"], scientificName: "Equisetum arvense", category: "vegetable", nature: "neutral", flavor: ["sweet", "bitter"], element: "wood", meridians: ["liver", "lung"], effects: ["疏風散熱", "明目退翳"], contraindications: [], nutrition: { silica: "高含有", flavonoids: "含有" }, commonUses: ["佃煮", "天ぷら", "おひたし"], preparationMethods: ["茹でる", "煮る", "揚げる"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "ツナ缶", nameEn: "Canned Tuna", nameAlt: ["ツナカン"], scientificName: "Thunnus spp.", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "liver", "kidney"], effects: ["補虚労", "益気血"], contraindications: [], nutrition: { calories: 267, protein: 17.7, EPA_DHA: "含有" }, commonUses: ["サラダ", "サンドイッチ", "パスタ"], preparationMethods: ["そのまま", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "とうがん", nameEn: "Winter Melon", nameAlt: ["冬瓜", "トウガン"], scientificName: "Benincasa hispida", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "water", meridians: ["lung", "large_intestine", "bladder"], effects: ["清熱利水", "消腫解毒"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 16, water: 95.2, potassium: 200 }, commonUses: ["スープ", "煮物", "炒め物"], preparationMethods: ["煮る", "炒める"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "とうふ", nameEn: "Tofu", nameAlt: ["豆腐", "トウフ"], scientificName: "Glycine max", category: "protein", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "large_intestine"], effects: ["益気和中", "生津潤燥", "清熱解毒"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 72, protein: 6.6, calcium: 120, isoflavones: "含有" }, commonUses: ["味噌汁", "冷奴", "炒め物"], preparationMethods: ["そのまま", "煮る", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "どじょう", nameEn: "Loach", nameAlt: ["泥鰌", "ドジョウ"], scientificName: "Misgurnus anguillicaudatus", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["spleen", "liver"], effects: ["補中益気", "祛湿退黄", "強筋壮骨"], contraindications: [], nutrition: { calories: 79, protein: 17.9, calcium: 1100, vitaminB12: "極高含有" }, commonUses: ["柳川鍋", "佃煮"], preparationMethods: ["煮る", "蒸す"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "とびうお", nameEn: "Flying Fish", nameAlt: ["飛魚", "トビウオ"], scientificName: "Cypselurus agoo", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾開胃"], contraindications: [], nutrition: { calories: 96, protein: 21.0, EPA_DHA: "含有" }, commonUses: ["だし", "刺身", "すり身"], preparationMethods: ["煮る", "生食", "すりつぶす"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "とりレバー", nameEn: "Chicken Liver", nameAlt: ["鶏肝", "トリレバー"], scientificName: "Gallus gallus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["liver", "kidney"], effects: ["補肝腎", "益精血", "明目"], contraindications: ["高尿酸者慎用"], nutrition: { calories: 111, protein: 18.9, iron: 9.0, vitaminA: "極高含有" }, commonUses: ["焼き鳥", "レバニラ", "煮物"], preparationMethods: ["焼く", "炒める", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] }
];

export async function insertBatch2() {
  console.log("🌱 Inserting Batch 2: や〜わ + additional (80 ingredients)...");
  
  try {
    let count = 0;
    for (const ingredient of batch2Ingredients) {
      await db.insert(ingredients).values(ingredient);
      count++;
      if (count % 10 === 0) {
        console.log(`   Inserted ${count}/${batch2Ingredients.length} ingredients...`);
      }
    }
    
    console.log(`✅ Batch 2 complete: ${count} ingredients inserted`);
    return count;
  } catch (error) {
    console.error("❌ Error inserting batch 2:", error);
    throw error;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  insertBatch2()
    .then((count) => {
      console.log(`🎉 Batch 2 populated with ${count} ingredients!`);
      process.exit(0);
    })
    .catch((error) => {
      console.error("💥 Failed to populate batch 2:", error);
      process.exit(1);
    });
}