import { db } from "./db";
import { ingredients } from "@shared/schema";
import { type InsertIngredient } from "@shared/schema";

// 薬膳食典 バッチ1: か行〜さ行の主要食材（100種類）
const batch1Ingredients: InsertIngredient[] = [
  // か行続き
  { name: "かつお", nameEn: "Skipjack Tuna", nameAlt: ["鰹", "カツオ"], scientificName: "Katsuwonus pelamis", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "健脾開胃", "強筋骨"], contraindications: [], nutrition: { calories: 114, protein: 25.8, EPA_DHA: "高含有" }, commonUses: ["刺身", "たたき", "だし"], preparationMethods: ["生食", "焼く", "煮る"], bestSeasons: ["spring", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "かに", nameEn: "Crab", nameAlt: ["蟹", "カニ"], scientificName: "Portunus trituberculatus", category: "protein", nature: "cold", flavor: ["salty"], element: "water", meridians: ["liver", "stomach"], effects: ["清熱散血", "滋陰補骨"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 83, protein: 18.4, taurine: "高含有" }, commonUses: ["茹で蟹", "蟹すき", "カニクリーム"], preparationMethods: ["茹でる", "蒸す", "煮る"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "かれい", nameEn: "Flounder", nameAlt: ["鰈", "カレイ"], scientificName: "Platichthys stellatus", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["spleen", "stomach"], effects: ["健脾補虚", "益気和中"], contraindications: [], nutrition: { calories: 95, protein: 19.6, taurine: "含有" }, commonUses: ["煮付け", "塩焼き", "唐揚げ"], preparationMethods: ["煮る", "焼く", "揚げる"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "きくらげ", nameEn: "Wood Ear Mushroom", nameAlt: ["木耳", "キクラゲ"], scientificName: "Auricularia auricula", category: "mushroom", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["補気血", "潤燥", "涼血止血"], contraindications: [], nutrition: { calories: 13, iron: 0.7, calcium: 82, fiber: 7.4 }, commonUses: ["炒め物", "スープ", "酢の物"], preparationMethods: ["水で戻す", "炒める", "茹でる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "きゅうり", nameEn: "Cucumber", nameAlt: ["胡瓜", "キュウリ"], scientificName: "Cucumis sativus", category: "vegetable", nature: "cold", flavor: ["sweet"], element: "water", meridians: ["stomach", "bladder"], effects: ["清熱利水", "解毒消腫"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 14, water: 95.4, potassium: 200 }, commonUses: ["サラダ", "漬物", "酢の物"], preparationMethods: ["生食", "漬ける"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "ぎんなん", nameEn: "Ginkgo Nut", nameAlt: ["銀杏", "ギンナン"], scientificName: "Ginkgo biloba", category: "nut", nature: "neutral", flavor: ["sweet", "bitter"], element: "metal", meridians: ["lung", "kidney"], effects: ["斂肺定喘", "止帯濁", "縮小便"], contraindications: ["小児多食禁忌", "生食禁忌"], nutrition: { calories: 187, carbohydrates: 38.0, ginkgotoxin: "含有" }, commonUses: ["茶碗蒸し", "炒め物", "串焼き"], preparationMethods: ["茹でる", "炒める", "焼く"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "くこ", nameEn: "Goji Berry", nameAlt: ["枸杞", "クコ"], scientificName: "Lycium barbarum", category: "herb", nature: "neutral", flavor: ["sweet"], element: "wood", meridians: ["liver", "kidney"], effects: ["滋補肝腎", "益精明目", "潤肺止咳"], contraindications: ["脾虚便溏者慎用"], nutrition: { betaCarotene: "高含有", polysaccharides: "含有", zeaxanthin: "高含有" }, commonUses: ["薬膳スープ", "お茶", "デザート"], preparationMethods: ["煎じる", "煮る", "浸す"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "くり", nameEn: "Chestnut", nameAlt: ["栗", "クリ"], scientificName: "Castanea crenata", category: "nut", nature: "warm", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "kidney"], effects: ["補腎強筋", "健脾養胃"], contraindications: ["気滞腹脹者慎用"], nutrition: { calories: 164, carbohydrates: 36.9, fiber: 4.2 }, commonUses: ["甘露煮", "栗ご飯", "モンブラン"], preparationMethods: ["茹でる", "焼く", "蒸す"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "くるみ", nameEn: "Walnut", nameAlt: ["胡桃", "クルミ"], scientificName: "Juglans regia", category: "nut", nature: "warm", flavor: ["sweet"], element: "water", meridians: ["kidney", "lung"], effects: ["補腎固精", "温肺定喘", "潤腸通便"], contraindications: ["痰火喘嗽者忌用"], nutrition: { calories: 674, fat: 68.8, omega3: "高含有" }, commonUses: ["お菓子", "料理の具材", "おつまみ"], preparationMethods: ["炒る", "砕く"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "くわい", nameEn: "Arrowhead", nameAlt: ["慈姑", "クワイ"], scientificName: "Sagittaria trifolia", category: "vegetable", nature: "cool", flavor: ["sweet", "bitter"], element: "water", meridians: ["heart", "liver"], effects: ["清熱解毒", "利水消腫"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 126, carbohydrates: 28.3, potassium: 600 }, commonUses: ["煮物", "揚げ物"], preparationMethods: ["茹でる", "煮る", "揚げる"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  
  // け・こ行
  { name: "ごぼう", nameEn: "Burdock Root", nameAlt: ["牛蒡", "ゴボウ"], scientificName: "Arctium lappa", category: "vegetable", nature: "cool", flavor: ["bitter", "sweet"], element: "metal", meridians: ["lung", "stomach"], effects: ["疏散風熱", "宣肺透疹", "解毒利咽"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 65, fiber: 5.7, potassium: 320, inulin: "含有" }, commonUses: ["煮物", "きんぴら", "天ぷら"], preparationMethods: ["煮る", "炒める", "揚げる"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  { name: "ごま", nameEn: "Sesame", nameAlt: ["胡麻", "ゴマ"], scientificName: "Sesamum indicum", category: "seed", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["liver", "kidney"], effects: ["補肝腎", "益精血", "潤燥滑腸"], contraindications: ["便溏者慎用"], nutrition: { calories: 578, protein: 19.8, calcium: 1200, sesamin: "高含有" }, commonUses: ["ごま塩", "すりごま", "お菓子"], preparationMethods: ["炒る", "擂り潰す"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "こまつな", nameEn: "Japanese Mustard Spinach", nameAlt: ["小松菜", "コマツナ"], scientificName: "Brassica rapa var. perviridis", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "wood", meridians: ["liver", "stomach"], effects: ["清熱解毒", "利水消腫"], contraindications: [], nutrition: { calories: 14, calcium: 170, betaCarotene: 3100 }, commonUses: ["おひたし", "炒め物", "味噌汁"], preparationMethods: ["茹でる", "炒める"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "こんにゃく", nameEn: "Konjac", nameAlt: ["蒟蒻", "コンニャク"], scientificName: "Amorphophallus konjac", category: "vegetable", nature: "cold", flavor: ["spicy"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["化痰消積", "解毒消腫", "通便"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 5, fiber: 2.2, glucomannan: "高含有" }, commonUses: ["おでん", "煮物", "刺身"], preparationMethods: ["茹でる", "煮る"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "こんぶ", nameEn: "Kelp", nameAlt: ["昆布", "コンブ"], scientificName: "Laminaria japonica", category: "seaweed", nature: "cold", flavor: ["salty"], element: "water", meridians: ["liver", "stomach", "kidney"], effects: ["軟堅散結", "消痰利水"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 145, iodine: "高含有", alginic_acid: "高含有" }, commonUses: ["だし", "煮物", "佃煮"], preparationMethods: ["煮る", "浸す"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  // さ行
  { name: "さけ", nameEn: "Salmon", nameAlt: ["鮭", "サケ"], scientificName: "Oncorhynchus keta", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補虚労", "健脾胃", "暖中"], contraindications: [], nutrition: { calories: 133, protein: 22.3, EPA: 260, DHA: 820, astaxanthin: "含有" }, commonUses: ["塩焼き", "刺身", "ちゃんちゃん焼き"], preparationMethods: ["焼く", "生食", "煮る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "さつまいも", nameEn: "Sweet Potato", nameAlt: ["薩摩芋", "サツマイモ"], scientificName: "Ipomoea batatas", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "kidney"], effects: ["補中益気", "生津潤燥", "通便"], contraindications: ["湿痰壅盛者慎用"], nutrition: { calories: 132, fiber: 2.3, betaCarotene: 23000 }, commonUses: ["焼き芋", "煮物", "天ぷら"], preparationMethods: ["焼く", "蒸す", "煮る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "さといも", nameEn: "Taro", nameAlt: ["里芋", "サトイモ"], scientificName: "Colocasia esculenta", category: "vegetable", nature: "neutral", flavor: ["sweet", "spicy"], element: "earth", meridians: ["stomach", "large_intestine"], effects: ["和胃健脾", "化痰軟堅"], contraindications: [], nutrition: { calories: 58, fiber: 2.3, galactan: "含有" }, commonUses: ["煮物", "汁物", "揚げ物"], preparationMethods: ["煮る", "蒸す", "揚げる"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  { name: "さば", nameEn: "Mackerel", nameAlt: ["鯖", "サバ"], scientificName: "Scomber japonicus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "強筋骨", "利水消腫"], contraindications: ["皮膚病患者慎用"], nutrition: { calories: 247, protein: 20.6, EPA: 1214, DHA: 1781 }, commonUses: ["塩焼き", "味噌煮", "しめ鯖"], preparationMethods: ["焼く", "煮る", "漬ける"], bestSeasons: ["autumn", "winter"], synergisticWith: [], conflictsWith: [] },
  { name: "さやいんげん", nameEn: "Green Bean", nameAlt: ["莢隠元", "サヤインゲン"], scientificName: "Phaseolus vulgaris", category: "legume", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "kidney"], effects: ["健脾化湿", "利水消腫"], contraindications: [], nutrition: { calories: 23, protein: 1.8, folate: 16 }, commonUses: ["炒め物", "茹で物", "天ぷら"], preparationMethods: ["茹でる", "炒める", "揚げる"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "さわら", nameEn: "Spanish Mackerel", nameAlt: ["鰆", "サワラ"], scientificName: "Scomberomorus niphonius", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["spleen", "stomach"], effects: ["健脾開胃", "補虚労"], contraindications: [], nutrition: { calories: 177, protein: 20.1, EPA_DHA: "含有" }, commonUses: ["西京焼き", "塩焼き", "刺身"], preparationMethods: ["焼く", "漬ける", "生食"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "さんしょう", nameEn: "Japanese Pepper", nameAlt: ["山椒", "サンショウ"], scientificName: "Zanthoxylum piperitum", category: "spice", nature: "hot", flavor: ["spicy"], element: "fire", meridians: ["spleen", "stomach", "kidney"], effects: ["温中止痛", "殺虫止痒"], contraindications: ["陰虚火旺者忌用"], nutrition: { sanshool: "含有", essential_oils: "含有" }, commonUses: ["薬味", "調味料"], preparationMethods: ["乾燥", "粉末化"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "しいたけ", nameEn: "Shiitake Mushroom", nameAlt: ["椎茸", "シイタケ"], scientificName: "Lentinula edodes", category: "mushroom", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["stomach", "liver"], effects: ["補気血", "健脾和胃", "化痰理気"], contraindications: [], nutrition: { calories: 19, fiber: 4.2, ergosterol: "高含有", lentinan: "含有" }, commonUses: ["煮物", "炒め物", "だし"], preparationMethods: ["茹でる", "炒める", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "しじみ", nameEn: "Freshwater Clam", nameAlt: ["蜆", "シジミ"], scientificName: "Corbicula japonica", category: "protein", nature: "cold", flavor: ["sweet", "salty"], element: "water", meridians: ["liver", "kidney"], effects: ["清熱利湿", "滋陰明目"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 51, protein: 7.5, iron: 5.3, ornithine: "高含有", taurine: "高含有" }, commonUses: ["味噌汁", "酒蒸し", "佃煮"], preparationMethods: ["煮る", "蒸す"], bestSeasons: ["winter", "spring"], synergisticWith: [], conflictsWith: [] },
  { name: "ししとう", nameEn: "Shishito Pepper", nameAlt: ["獅子唐", "シシトウ"], scientificName: "Capsicum annuum", category: "vegetable", nature: "warm", flavor: ["spicy"], element: "fire", meridians: ["spleen", "stomach"], effects: ["温中散寒", "開胃消食"], contraindications: ["陰虚火旺者慎用"], nutrition: { calories: 27, vitaminC: 57, capsaicin: "含有" }, commonUses: ["焼き物", "天ぷら", "炒め物"], preparationMethods: ["焼く", "揚げる", "炒める"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "しそ", nameEn: "Perilla", nameAlt: ["紫蘇", "シソ"], scientificName: "Perilla frutescens", category: "herb", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "spleen"], effects: ["発表散寒", "行気和胃", "解魚蟹毒"], contraindications: ["気虚者慎用"], nutrition: { betaCarotene: 11000, perillaldehyde: "高含有" }, commonUses: ["薬味", "天ぷら", "漬物"], preparationMethods: ["生食", "揚げる", "漬ける"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "しめじ", nameEn: "Shimeji Mushroom", nameAlt: ["湿地", "シメジ"], scientificName: "Hypsizygus marmoreus", category: "mushroom", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["stomach", "large_intestine"], effects: ["補益胃腸", "理気化痰"], contraindications: [], nutrition: { calories: 18, fiber: 3.7, ergothioneine: "含有" }, commonUses: ["炒め物", "鍋物", "スープ"], preparationMethods: ["炒める", "煮る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "しょうが", nameEn: "Ginger", nameAlt: ["生姜", "ショウガ"], scientificName: "Zingiber officinale", category: "spice", nature: "warm", flavor: ["spicy"], element: "fire", meridians: ["lung", "spleen", "stomach"], effects: ["発汗解表", "温中止嘔", "温肺止咳"], contraindications: ["陰虚内熱者慎用"], nutrition: { gingerol: "高含有", shogaol: "含有" }, commonUses: ["薬味", "調味料", "お茶"], preparationMethods: ["すりおろす", "切る", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "しらす", nameEn: "Whitebait", nameAlt: ["白子", "シラス"], scientificName: "Engraulis japonicus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["補中益気", "強筋骨"], contraindications: [], nutrition: { calories: 113, protein: 23.1, calcium: 210 }, commonUses: ["丼物", "おにぎり", "サラダ"], preparationMethods: ["茹でる", "乾燥"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "すいか", nameEn: "Watermelon", nameAlt: ["西瓜", "スイカ"], scientificName: "Citrullus lanatus", category: "fruit", nature: "cold", flavor: ["sweet"], element: "water", meridians: ["heart", "stomach", "bladder"], effects: ["清熱解暑", "除煩止渇", "利小便"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 37, water: 89.6, citrulline: "含有", lycopene: "含有" }, commonUses: ["生食", "ジュース"], preparationMethods: ["生食", "冷やす"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  
  // 続く(30種類完了 + 上記で計61種類)
  { name: "すずき", nameEn: "Sea Bass", nameAlt: ["鱸", "スズキ"], scientificName: "Lateolabrax japonicus", category: "protein", nature: "neutral", flavor: ["sweet"], element: "water", meridians: ["liver", "spleen", "kidney"], effects: ["補肝腎", "益脾胃", "化痰止咳"], contraindications: [], nutrition: { calories: 123, protein: 19.8, EPA_DHA: "含有" }, commonUses: ["刺身", "塩焼き", "洗い"], preparationMethods: ["生食", "焼く", "煮る"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "セロリ", nameEn: "Celery", nameAlt: ["celery"], scientificName: "Apium graveolens", category: "vegetable", nature: "cool", flavor: ["sweet", "bitter"], element: "wood", meridians: ["liver", "stomach", "bladder"], effects: ["清熱平肝", "利水消腫"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 15, fiber: 1.5, apigenin: "含有" }, commonUses: ["サラダ", "炒め物", "スープ"], preparationMethods: ["生食", "炒める", "煮る"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "そば", nameEn: "Buckwheat", nameAlt: ["蕎麦", "ソバ"], scientificName: "Fagopyrum esculentum", category: "grain", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "large_intestine"], effects: ["健脾消積", "下気寬腸"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 344, protein: 12.0, rutin: "高含有" }, commonUses: ["蕎麦", "そばがき", "蕎麦茶"], preparationMethods: ["茹でる", "挽く"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "そらまめ", nameEn: "Fava Bean", nameAlt: ["空豆", "ソラマメ"], scientificName: "Vicia faba", category: "legume", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["健脾利湿", "補中益気"], contraindications: ["G6PD欠損症患者禁用"], nutrition: { calories: 108, protein: 10.9, fiber: 2.6 }, commonUses: ["茹で豆", "炒め物", "煮豆"], preparationMethods: ["茹でる", "炒める", "煮る"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  
  { name: "たい", nameEn: "Sea Bream", nameAlt: ["鯛", "タイ"], scientificName: "Pagrus major", category: "protein", nature: "neutral", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["健脾益気", "和胃調中"], contraindications: [], nutrition: { calories: 142, protein: 20.6, EPA_DHA: "含有" }, commonUses: ["刺身", "塩焼き", "鯛めし"], preparationMethods: ["生食", "焼く", "煮る", "蒸す"], bestSeasons: ["spring", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "たけのこ", nameEn: "Bamboo Shoot", nameAlt: ["筍", "タケノコ"], scientificName: "Phyllostachys edulis", category: "vegetable", nature: "cold", flavor: ["sweet"], element: "wood", meridians: ["stomach", "large_intestine"], effects: ["清熱化痰", "利膈爽胃"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 26, fiber: 2.8, potassium: 520 }, commonUses: ["煮物", "炒め物", "炊き込みご飯"], preparationMethods: ["茹でる", "煮る", "炒める"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "たこ", nameEn: "Octopus", nameAlt: ["蛸", "タコ"], scientificName: "Octopus vulgaris", category: "protein", nature: "cool", flavor: ["sweet", "salty"], element: "water", meridians: ["liver", "kidney"], effects: ["補気養血", "収斂生肌"], contraindications: [], nutrition: { calories: 76, protein: 16.4, taurine: "高含有" }, commonUses: ["刺身", "たこ焼き", "酢の物"], preparationMethods: ["生食", "茹でる", "焼く"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "たまねぎ", nameEn: "Onion", nameAlt: ["玉葱", "タマネギ"], scientificName: "Allium cepa", category: "vegetable", nature: "warm", flavor: ["spicy", "sweet"], element: "metal", meridians: ["lung", "stomach"], effects: ["発散風寒", "健胃消食", "殺虫解毒"], contraindications: [], nutrition: { calories: 37, quercetin: "高含有", sulfur_compounds: "含有" }, commonUses: ["炒め物", "サラダ", "スープ"], preparationMethods: ["炒める", "煮る", "生食"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "だいこん", nameEn: "Daikon Radish", nameAlt: ["大根", "ダイコン"], scientificName: "Raphanus sativus", category: "vegetable", nature: "cool", flavor: ["sweet", "spicy"], element: "metal", meridians: ["lung", "stomach"], effects: ["消食下気", "化痰止咳", "清熱生津"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 18, vitaminC: 12, fiber: 1.4, amylase: "含有" }, commonUses: ["煮物", "大根おろし", "漬物"], preparationMethods: ["煮る", "おろす", "漬ける", "生食"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "だいず", nameEn: "Soybean", nameAlt: ["大豆", "ダイズ"], scientificName: "Glycine max", category: "legume", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "large_intestine"], effects: ["健脾寛中", "潤燥消水", "清熱解毒"], contraindications: [], nutrition: { calories: 417, protein: 35.3, isoflavones: "高含有" }, commonUses: ["豆腐", "納豆", "味噌", "醤油"], preparationMethods: ["茹でる", "発酵", "搾る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ちんげんさい", nameEn: "Bok Choy", nameAlt: ["青梗菜", "チンゲンサイ"], scientificName: "Brassica rapa subsp. chinensis", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "wood", meridians: ["stomach", "large_intestine"], effects: ["清熱除煩", "通利胃腸"], contraindications: [], nutrition: { calories: 9, calcium: 100, betaCarotene: 2000 }, commonUses: ["炒め物", "スープ", "煮物"], preparationMethods: ["炒める", "茹でる", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "とうがらし", nameEn: "Chili Pepper", nameAlt: ["唐辛子", "トウガラシ"], scientificName: "Capsicum annuum", category: "spice", nature: "hot", flavor: ["spicy"], element: "fire", meridians: ["heart", "spleen"], effects: ["温中散寒", "開胃消食", "除湿祛寒"], contraindications: ["陰虚火旺者忌用"], nutrition: { capsaicin: "高含有", vitaminC: "高含有" }, commonUses: ["調味料", "薬味"], preparationMethods: ["乾燥", "粉末化"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "とうもろこし", nameEn: "Corn", nameAlt: ["玉蜀黍", "トウモロコシ"], scientificName: "Zea mays", category: "grain", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "large_intestine"], effects: ["調中開胃", "益肺寧心", "利水通淋"], contraindications: [], nutrition: { calories: 92, fiber: 3.0, lutein: "含有" }, commonUses: ["茹で玉蜀黍", "コーンスープ", "ポップコーン"], preparationMethods: ["茹でる", "焼く", "煮る"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "トマト", nameEn: "Tomato", nameAlt: ["tomato"], scientificName: "Solanum lycopersicum", category: "vegetable", nature: "cool", flavor: ["sweet", "sour"], element: "fire", meridians: ["liver", "spleen", "stomach"], effects: ["生津止渇", "健胃消食", "涼血平肝"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 19, lycopene: "高含有", vitaminC: 15 }, commonUses: ["サラダ", "ソース", "ジュース"], preparationMethods: ["生食", "煮る", "炒める"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "とり肉", nameEn: "Chicken", nameAlt: ["鶏肉", "トリニク"], scientificName: "Gallus gallus domesticus", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "stomach"], effects: ["温中補虚", "益気補精", "補髄添精"], contraindications: ["実熱証者慎用"], nutrition: { calories: 200, protein: 19.5, collagen: "含有" }, commonUses: ["焼き鳥", "唐揚げ", "鍋物"], preparationMethods: ["焼く", "煮る", "揚げる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "なす", nameEn: "Eggplant", nameAlt: ["茄子", "ナス"], scientificName: "Solanum melongena", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "large_intestine"], effects: ["清熱活血", "消腫止痛"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 22, anthocyanins: "含有", potassium: 220 }, commonUses: ["焼きなす", "煮物", "天ぷら"], preparationMethods: ["焼く", "煮る", "炒める", "揚げる"], bestSeasons: ["summer", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "なつめ", nameEn: "Jujube", nameAlt: ["棗", "ナツメ"], scientificName: "Ziziphus jujuba", category: "fruit", nature: "warm", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["補中益気", "養血安神", "緩和薬性"], contraindications: ["湿熱内盛者慎用"], nutrition: { calories: 287, fiber: 12.5, cyclic_AMP: "含有" }, commonUses: ["薬膳料理", "お茶", "お菓子"], preparationMethods: ["乾燥", "煮る", "蒸す"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "なまこ", nameEn: "Sea Cucumber", nameAlt: ["海鼠", "ナマコ"], scientificName: "Apostichopus japonicus", category: "protein", nature: "warm", flavor: ["salty"], element: "water", meridians: ["kidney", "heart"], effects: ["補腎益精", "養血潤燥"], contraindications: ["脾胃虚弱者慎用"], nutrition: { calories: 23, protein: 4.6, collagen: "高含有", saponins: "含有" }, commonUses: ["酢の物", "中華料理"], preparationMethods: ["茹でる", "煮る", "酢漬け"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "なめこ", nameEn: "Nameko Mushroom", nameAlt: ["滑子", "ナメコ"], scientificName: "Pholiota microspora", category: "mushroom", nature: "cool", flavor: ["sweet"], element: "water", meridians: ["stomach", "large_intestine"], effects: ["補益胃腸", "化痰利水"], contraindications: [], nutrition: { calories: 15, mucopolysaccharides: "高含有", fiber: 3.4 }, commonUses: ["味噌汁", "おろし和え", "鍋物"], preparationMethods: ["茹でる", "煮る"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "なんきんまめ", nameEn: "Peanut", nameAlt: ["南京豆", "ナンキンマメ", "ピーナッツ"], scientificName: "Arachis hypogaea", category: "nut", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "lung"], effects: ["潤肺化痰", "和胃", "補脾益気"], contraindications: ["痰湿内盛者慎用"], nutrition: { calories: 562, protein: 25.4, oleic_acid: "高含有" }, commonUses: ["おつまみ", "お菓子", "ピーナッツバター"], preparationMethods: ["炒る", "茹でる", "搾る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "にがうり", nameEn: "Bitter Melon", nameAlt: ["苦瓜", "ニガウリ", "ゴーヤ"], scientificName: "Momordica charantia", category: "vegetable", nature: "cold", flavor: ["bitter"], element: "fire", meridians: ["heart", "spleen", "stomach"], effects: ["清暑解熱", "明目解毒"], contraindications: ["脾胃虚寒者慎用", "孕婦慎用"], nutrition: { calories: 17, vitaminC: 76, momordicin: "含有" }, commonUses: ["炒め物", "酢の物", "ジュース"], preparationMethods: ["炒める", "茹でる", "生食"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "にら", nameEn: "Chinese Chive", nameAlt: ["韮", "ニラ"], scientificName: "Allium tuberosum", category: "vegetable", nature: "warm", flavor: ["spicy"], element: "wood", meridians: ["liver", "stomach", "kidney"], effects: ["温中行気", "散血解毒", "補肝腎"], contraindications: ["陰虚火旺者慎用"], nutrition: { calories: 21, betaCarotene: 3500, allicin: "含有" }, commonUses: ["炒め物", "餃子", "スープ"], preparationMethods: ["炒める", "茹でる", "生食"], bestSeasons: ["spring"], synergisticWith: [], conflictsWith: [] },
  { name: "にんじん", nameEn: "Carrot", nameAlt: ["人参", "ニンジン"], scientificName: "Daucus carota", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["lung", "spleen"], effects: ["健脾和中", "滋肝明目", "清熱解毒"], contraindications: [], nutrition: { calories: 39, betaCarotene: 8600, fiber: 2.5 }, commonUses: ["煮物", "サラダ", "ジュース"], preparationMethods: ["煮る", "炒める", "生食"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "にんにく", nameEn: "Garlic", nameAlt: ["大蒜", "ニンニク"], scientificName: "Allium sativum", category: "spice", nature: "hot", flavor: ["spicy"], element: "fire", meridians: ["spleen", "stomach", "lung"], effects: ["温中健胃", "消食理気", "解毒殺虫"], contraindications: ["陰虚火旺者忌用", "目疾患者忌用"], nutrition: { allicin: "高含有", selenium: "含有", scordinin: "含有" }, commonUses: ["調味料", "薬味", "健康食品"], preparationMethods: ["すりおろす", "刻む", "炒める"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ねぎ", nameEn: "Welsh Onion", nameAlt: ["葱", "ネギ"], scientificName: "Allium fistulosum", category: "vegetable", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "stomach"], effects: ["発汗解表", "散寒通陽", "解毒散結"], contraindications: ["表虚多汗者慎用"], nutrition: { calories: 28, allicin: "含有", fructans: "含有" }, commonUses: ["薬味", "鍋物", "炒め物"], preparationMethods: ["切る", "焼く", "煮る"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "のり", nameEn: "Nori Seaweed", nameAlt: ["海苔", "ノリ"], scientificName: "Porphyra yezoensis", category: "seaweed", nature: "cold", flavor: ["sweet", "salty"], element: "water", meridians: ["lung", "kidney"], effects: ["化痰軟堅", "清熱利水"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 188, protein: 41.4, iron: 11.4, EPA: "含有" }, commonUses: ["おにぎり", "寿司", "ふりかけ"], preparationMethods: ["焼く", "乾燥"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "はくさい", nameEn: "Chinese Cabbage", nameAlt: ["白菜", "ハクサイ"], scientificName: "Brassica rapa subsp. pekinensis", category: "vegetable", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["stomach", "large_intestine"], effects: ["清熱除煩", "利尿通便", "養胃生津"], contraindications: [], nutrition: { calories: 14, vitaminC: 19, fiber: 1.3 }, commonUses: ["鍋物", "漬物", "炒め物"], preparationMethods: ["煮る", "漬ける", "炒める"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "はちみつ", nameEn: "Honey", nameAlt: ["蜂蜜", "ハチミツ"], scientificName: "Apis mellifera", category: "sweetener", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["lung", "spleen", "large_intestine"], effects: ["補中緩急", "潤肺止咳", "潤腸通便", "解毒"], contraindications: ["湿阻中満者慎用", "1歳未満児禁用"], nutrition: { calories: 294, fructose: "高含有", glucose: "高含有", enzymes: "含有" }, commonUses: ["甘味料", "お茶", "お菓子"], preparationMethods: ["そのまま", "溶かす"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "バナナ", nameEn: "Banana", nameAlt: ["banana"], scientificName: "Musa acuminata", category: "fruit", nature: "cold", flavor: ["sweet"], element: "earth", meridians: ["spleen", "large_intestine"], effects: ["清熱潤腸", "解毒生津"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 86, potassium: 360, tryptophan: "含有" }, commonUses: ["生食", "スムージー", "お菓子"], preparationMethods: ["生食", "焼く"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ピーマン", nameEn: "Bell Pepper", nameAlt: ["piment"], scientificName: "Capsicum annuum", category: "vegetable", nature: "warm", flavor: ["spicy", "sweet"], element: "fire", meridians: ["spleen", "heart"], effects: ["温中散寒", "開胃消食"], contraindications: ["陰虚火旺者慎用"], nutrition: { calories: 22, vitaminC: 76, capsanthin: "含有" }, commonUses: ["炒め物", "サラダ", "肉詰め"], preparationMethods: ["炒める", "焼く", "生食"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  { name: "ひじき", nameEn: "Hijiki Seaweed", nameAlt: ["鹿尾菜", "ヒジキ"], scientificName: "Sargassum fusiforme", category: "seaweed", nature: "cold", flavor: ["salty"], element: "water", meridians: ["liver", "kidney"], effects: ["軟堅散結", "利水消腫"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 149, calcium: 1400, iron: 55.0, fiber: 43.3 }, commonUses: ["煮物", "サラダ", "炊き込みご飯"], preparationMethods: ["水で戻す", "煮る"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ぶた肉", nameEn: "Pork", nameAlt: ["豚肉", "ブタニク"], scientificName: "Sus scrofa domesticus", category: "protein", nature: "neutral", flavor: ["sweet", "salty"], element: "water", meridians: ["spleen", "stomach", "kidney"], effects: ["滋陰潤燥", "補腎養血"], contraindications: ["湿熱痰滞者慎用"], nutrition: { calories: 263, protein: 19.3, vitaminB1: 0.69 }, commonUses: ["生姜焼き", "豚カツ", "しゃぶしゃぶ"], preparationMethods: ["焼く", "煮る", "揚げる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "ぶどう", nameEn: "Grape", nameAlt: ["葡萄", "ブドウ"], scientificName: "Vitis vinifera", category: "fruit", nature: "neutral", flavor: ["sweet", "sour"], element: "wood", meridians: ["lung", "spleen", "kidney"], effects: ["補気血", "強筋骨", "利小便"], contraindications: ["脾虚便溏者慎用"], nutrition: { calories: 59, polyphenols: "高含有", resveratrol: "含有" }, commonUses: ["生食", "ワイン", "レーズン"], preparationMethods: ["生食", "乾燥", "発酵"], bestSeasons: ["summer", "autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "ブロッコリー", nameEn: "Broccoli", nameAlt: ["broccoli"], scientificName: "Brassica oleracea var. italica", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "wood", meridians: ["liver", "kidney", "spleen"], effects: ["補腎填精", "健脾和胃", "清熱解毒"], contraindications: [], nutrition: { calories: 33, vitaminC: 120, sulforaphane: "高含有", betaCarotene: 810 }, commonUses: ["サラダ", "炒め物", "シチュー"], preparationMethods: ["茹でる", "炒める", "蒸す"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  
  { name: "ほうれんそう", nameEn: "Spinach", nameAlt: ["菠薐草", "ホウレンソウ"], scientificName: "Spinacia oleracea", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "wood", meridians: ["liver", "stomach", "large_intestine", "small_intestine"], effects: ["養血止血", "斂陰潤燥", "通利腸胃"], contraindications: ["脾虚便溏者慎用"], nutrition: { calories: 20, iron: 2.0, betaCarotene: 4200, lutein: "高含有" }, commonUses: ["おひたし", "炒め物", "サラダ"], preparationMethods: ["茹でる", "炒める", "生食"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "ほたて", nameEn: "Scallop", nameAlt: ["帆立", "ホタテ"], scientificName: "Mizuhopecten yessoensis", category: "protein", nature: "neutral", flavor: ["sweet", "salty"], element: "water", meridians: ["liver", "kidney"], effects: ["滋陰補腎", "調中消食"], contraindications: [], nutrition: { calories: 72, protein: 13.5, taurine: "高含有", glycogen: "含有" }, commonUses: ["刺身", "バター焼き", "フライ"], preparationMethods: ["生食", "焼く", "煮る", "揚げる"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  
  { name: "まいたけ", nameEn: "Maitake Mushroom", nameAlt: ["舞茸", "マイタケ"], scientificName: "Grifola frondosa", category: "mushroom", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["健脾益気", "化痰理気"], contraindications: [], nutrition: { calories: 16, fiber: 3.5, beta_glucans: "高含有", ergosterol: "含有" }, commonUses: ["炒め物", "鍋物", "天ぷら"], preparationMethods: ["炒める", "煮る", "揚げる"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "まぐろ", nameEn: "Tuna", nameAlt: ["鮪", "マグロ"], scientificName: "Thunnus orientalis", category: "protein", nature: "warm", flavor: ["sweet"], element: "fire", meridians: ["spleen", "liver", "kidney"], effects: ["補虚労", "強筋骨", "益精血"], contraindications: [], nutrition: { calories: 125, protein: 26.4, EPA: 27, DHA: 120, iron: 1.1 }, commonUses: ["刺身", "寿司", "ステーキ"], preparationMethods: ["生食", "焼く"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "まつたけ", nameEn: "Matsutake Mushroom", nameAlt: ["松茸", "マツタケ"], scientificName: "Tricholoma matsutake", category: "mushroom", nature: "neutral", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["益胃補虚", "理気化痰"], contraindications: [], nutrition: { calories: 23, fiber: 4.7, ergosterol: "高含有" }, commonUses: ["土瓶蒸し", "炊き込みご飯", "焼き物"], preparationMethods: ["焼く", "煮る", "蒸す"], bestSeasons: ["autumn"], synergisticWith: [], conflictsWith: [] },
  { name: "みかん", nameEn: "Mandarin Orange", nameAlt: ["蜜柑", "ミカン"], scientificName: "Citrus unshiu", category: "fruit", nature: "cool", flavor: ["sweet", "sour"], element: "wood", meridians: ["lung", "stomach"], effects: ["生津止渇", "潤肺化痰"], contraindications: ["脾虚便溏者慎用"], nutrition: { calories: 46, vitaminC: 32, hesperidin: "含有" }, commonUses: ["生食", "ジュース"], preparationMethods: ["生食"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  
  { name: "みそ", nameEn: "Miso", nameAlt: ["味噌", "ミソ"], scientificName: "Glycine max", category: "fermented", nature: "neutral", flavor: ["salty"], element: "earth", meridians: ["spleen", "stomach", "kidney"], effects: ["健脾和胃", "解毒", "調中益気"], contraindications: [], nutrition: { calories: 192, protein: 12.5, isoflavones: "含有", probiotics: "含有" }, commonUses: ["味噌汁", "調味料", "漬け床"], preparationMethods: ["溶かす", "和える"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] },
  { name: "みょうが", nameEn: "Japanese Ginger", nameAlt: ["茗荷", "ミョウガ"], scientificName: "Zingiber mioga", category: "vegetable", nature: "warm", flavor: ["spicy"], element: "metal", meridians: ["lung", "stomach"], effects: ["発汗解表", "理気和胃"], contraindications: [], nutrition: { calories: 12, alphaピネン: "含有" }, commonUses: ["薬味", "酢の物", "漬物"], preparationMethods: ["刻む", "漬ける"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  
  { name: "むぎ", nameEn: "Barley", nameAlt: ["麦", "ムギ"], scientificName: "Hordeum vulgare", category: "grain", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach"], effects: ["和胃消食", "回乳"], contraindications: ["授乳中の女性注意"], nutrition: { calories: 340, fiber: 9.6, beta_glucans: "高含有" }, commonUses: ["麦茶", "麦ご飯", "味噌"], preparationMethods: ["煮る", "炒る", "発酵"], bestSeasons: ["summer"], synergisticWith: [], conflictsWith: [] },
  
  { name: "もち米", nameEn: "Glutinous Rice", nameAlt: ["糯米", "モチゴメ"], scientificName: "Oryza sativa var. glutinosa", category: "grain", nature: "warm", flavor: ["sweet"], element: "earth", meridians: ["spleen", "stomach", "lung"], effects: ["補中益気", "温脾止瀉"], contraindications: ["湿熱痰火者慎用"], nutrition: { calories: 359, carbohydrates: 77.2, amylopectin: "高含有" }, commonUses: ["お餅", "赤飯", "おこわ"], preparationMethods: ["蒸す", "搗く", "炊く"], bestSeasons: ["winter"], synergisticWith: [], conflictsWith: [] },
  { name: "もやし", nameEn: "Bean Sprouts", nameAlt: ["萌やし", "モヤシ"], scientificName: "Vigna radiata", category: "vegetable", nature: "cool", flavor: ["sweet"], element: "earth", meridians: ["spleen", "large_intestine"], effects: ["清熱解毒", "利水消腫"], contraindications: ["脾胃虚寒者慎用"], nutrition: { calories: 14, vitaminC: 8, fiber: 1.3 }, commonUses: ["炒め物", "ナムル", "ラーメン"], preparationMethods: ["炒める", "茹でる"], bestSeasons: ["all"], synergisticWith: [], conflictsWith: [] }
];

export async function insertBatch1() {
  console.log("🌱 Inserting Batch 1: か〜も (70 ingredients)...");
  
  try {
    let count = 0;
    for (const ingredient of batch1Ingredients) {
      await db.insert(ingredients).values(ingredient);
      count++;
      if (count % 10 === 0) {
        console.log(`   Inserted ${count}/${batch1Ingredients.length} ingredients...`);
      }
    }
    
    console.log(`✅ Batch 1 complete: ${count} ingredients inserted`);
    return count;
  } catch (error) {
    console.error("❌ Error inserting batch 1:", error);
    throw error;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  insertBatch1()
    .then((count) => {
      console.log(`🎉 Batch 1 populated with ${count} ingredients!`);
      process.exit(0);
    })
    .catch((error) => {
      console.error("💥 Failed to populate batch 1:", error);
      process.exit(1);
    });
}